# Generated by Django 4.0.4 on 2022-05-27 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(blank=True, max_length=200, null=True)),
                ('skill_experiance_level', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, null=True, verbose_name=((1, 'NOT_COMPLETED'), (2, 'on_going'), (3, 'is_completed')))),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.skills')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=200, null=True)),
                ('project_requirements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.skills')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('current_projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.projects')),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.skills')),
            ],
        ),
    ]
