# Generated by Django 4.0.4 on 2022-05-27 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_rename_projects_project_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='employee_name',
        ),
    ]
