# Generated by Django 4.0.4 on 2022-05-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_rename_name_employee_employee_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_requirements',
        ),
        migrations.AddField(
            model_name='project',
            name='project_requirements',
            field=models.ManyToManyField(to='office.skill'),
        ),
    ]
