# Generated by Django 4.0.4 on 2022-05-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0004_remove_project_project_requirements_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='current_projects',
        ),
        migrations.AddField(
            model_name='employee',
            name='current_projects',
            field=models.ManyToManyField(to='office.project'),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='skills',
        ),
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.ManyToManyField(to='office.skill'),
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='skill',
        ),
        migrations.AddField(
            model_name='requirement',
            name='skill',
            field=models.ManyToManyField(to='office.skill'),
        ),
    ]
