# Generated by Django 4.0.4 on 2022-05-27 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0005_remove_employee_current_projects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_requirements',
        ),
        migrations.AddField(
            model_name='project',
            name='project_requirements',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='office.skill'),
            preserve_default=False,
        ),
    ]
