# Generated by Django 4.0.4 on 2022-05-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0007_remove_project_project_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_requirements',
            field=models.ManyToManyField(to='office.skill'),
        ),
    ]
