# Generated by Django 4.0.4 on 2022-05-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0010_alter_project_project_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='current_projects',
            field=models.ManyToManyField(blank=True, to='office.project'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='skills',
            field=models.ManyToManyField(blank=True, to='office.skill'),
        ),
    ]
