# Generated by Django 4.0.4 on 2022-05-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0012_rename_skill_experiance_level_skill_skill_experience_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_image',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
