# Generated by Django 4.0.4 on 2022-05-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0012_rename_skill_experiance_level_skill_skill_experience_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.CharField(default='employee@email.com', max_length=100, null=True),
        ),
    ]
