# Generated by Django 4.0.4 on 2022-05-28 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0013_employee_emp_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='emp_image',
        ),
    ]
