# Generated by Django 4.0.4 on 2022-05-28 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0013_employee_email'),
        ('office', '0014_remove_employee_emp_image'),
    ]

    operations = [
    ]
