# Generated by Django 4.0.4 on 2022-05-28 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0015_merge_20220528_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
